# Generated by Django 4.2.6 on 2023-10-17 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('27991f09-3048-48a6-994a-0320788fcd40'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
