# Generated by Django 4.2.6 on 2023-10-21 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CMS', '0003_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('a64be1d1-743b-4b26-addd-76cf1a6735f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
