# Generated by Django 4.2.6 on 2023-10-21 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_blog_post_author_blog_post_featured_blog_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('50cca76d-eacc-4ec7-9559-f39492b48ec1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
