# Generated by Django 4.2.6 on 2023-10-18 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_blog_post_author_blog_post_featured_blog_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('217a0201-3587-4ecf-ad88-051cf6b0a4fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
