# Generated by Django 4.2.6 on 2023-10-21 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('439b17ce-7b4f-4584-8991-7fb3eeb1f4a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
