# Generated by Django 4.2.6 on 2023-10-18 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('f6f35bb2-1b06-4d8a-9b41-55c7fbb7e753'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
