# Generated by Django 4.2.6 on 2023-10-18 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('b5d3aa8f-3776-4876-8616-b63926f4a657'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
