# Generated by Django 4.2.6 on 2023-10-25 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('c8b5bb88-e89d-45de-a2c6-fa13dbb8acb8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
