# Generated by Django 4.2.6 on 2023-10-25 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('cbed9411-14d7-4fd4-8642-5bf04dfa4903'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
