# Generated by Django 4.2.6 on 2023-10-25 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0009_alter_blog_post_image_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('82dfc47b-caa2-4fff-b76a-8dd11d149eaa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
