# Generated by Django 4.2.6 on 2023-10-30 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0010_alter_blog_post_image_alter_blog_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('5f5e1ca9-adaa-4c33-8fff-45d043894962'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
